### PR TITLE
Added the binds to support src port iteration

### PR DESCRIPTION
**Pull request by h3ct0r**
Hi,

This pull request is the corresponding update to the python bindings of the "src port iteration" pull request at the c++ project.

Regards!

### CODE REVIEW

**Comment by insomniacslk** [comment]
Just to be clear, this is pending merging of https://github.com/insomniacslk/dublin-traceroute/pull/34

**Comment by insomniacslk** [comment]
As mentioned in https://github.com/insomniacslk/dublin-traceroute/pull/34 , we also need to update the plotting function to correctly show that the port used for the flow identification is the source port, not the destination port

**Comment by h3ct0r** [comment]
Ok, I will check on that!

**Comment by h3ct0r** [comment]
Hi @insomniacslk sorry about the delay in the response, work has been hardcore lately! Can you please point me at the classes/commands I need to check for the plotting function to work correctly? For example, what's the output we should be expecting to have. Thanks!

**Comment by insomniacslk** [comment]
@h3ct0r , I .. apologize for having completely lost track of this. I have a few spare days and if you are still interested we can look at finishing this

**Comment by insomniacslk** [comment]
I've recreated it at https://github.com/insomniacslk/python-dublin-traceroute/pull/18 because the code diverged a lot since this patch

**Comment by insomniacslk** [comment]
closing this in favour of #18

**Comment by insomniacslk** [comment]
> Hi @insomniacslk sorry about the delay in the response, work has been hardcore lately! Can you please point me at the classes/commands I need to check for the plotting function to work correctly? For example, what's the output we should be expecting to have. Thanks!

Also sorry for misleading you with this - the JSON generation is done in the C++ library, so this should have been done in https://github.com/insomniacslk/dublin-traceroute/pull/34 instead. I'll patch that soon, and add tests

**Comment by insomniacslk** [comment]
done in #18

**Comment by h3ct0r** [comment]
> @h3ct0r , I .. apologize for having completely lost track of this. I have a few spare days and if you are still interested we can look at finishing this

Hi @insomniacslk, dont worry about it, its nice to see that the features got finally its way into the master! Let me know if I can help with anything more.

**Comment by insomniacslk** [comment]
thanks @h3ct0r !

> Let me know if I can help with anything more.

Please let me know if this works for you :) And any feedback in general is always appreciated

**Pull request closed without merging**
